<?php
/**
 * Marcin Klauza - Magento developer
 * http://www.marcinklauza.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to marcinklauza@gmail.com so we can send you a copy immediately.
 *
 * @category    Mklauza
 * @package     Mklauza_CustomProductUrls
 * @author      Marcin Klauza <marcinklauza@gmail.com>
 * @copyright   Copyright (c) 2015 (Marcin Klauza)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="js-tag-cloud inputTags-list">
    <?php echo $this->getAttributesCloudHtml() ?>
</div>
<br/>
<div class="js-pattern inputTags-list">
    <?php echo $this->getPatternHtml() ?>
</div>

<?php echo $this->getElement()->getElementHtml() ?>

<button onclick="return showExample()">Example</button>
<span id="js-example"></span>
<span id="loading"><span>.</span><span>.</span><span>.</span><span>.</span><span>.</span></span>
        
<script lang="Javascript">    
    
    function showExample() {
        var pattern = serializePattern();
        jQuery('#loading').show();
        jQuery('#js-example').html('');
        jQuery.ajax({
            method: 'get',
            url: '<?php echo $this->getExampleUrl() ?>',
            data: {
                pattern: pattern
            }
        }).success(function(data){
            jQuery('#loading').hide();
            if(typeof data !== 'undefined' && data.isSuccess) {
                jQuery('#js-example').text(data.exampleUrl);
            }
        });
        return false;
    }        
    prepareSave = function() {
        jQuery('#<?php echo $this->getElement()->getHtmlId() ?>').val(serializePattern());
    };
    
    jQuery(document).on('change', '.js-pattern', function(){
        prepareSave();
    });

    jQuery(document).on('change', '#mklauza_customproducturls_general_pattern_inherit', function() {
        this.checked ? disableFields() : enableFileds();
    });    
    
    jQuery(document).ready(function(){
        
        jQuery('.js-pattern').sortable({
            connectWith: '.js-tag-cloud',
            update: function(event, ui) {
                jQuery(this).validatePattern();
                prepareSave();
            },
            start: function(e, ui ){               
                ui.placeholder.width(ui.helper.width()+34);  
            },
        });

        jQuery('.js-tag-cloud').sortable({
            connectWith: '.js-pattern',
            start: function(e, ui ){              
                ui.placeholder.width(ui.helper.width()+34);                 
            },
        });      
        jQuery('.inputTags-field').adjustSize();
        jQuery('#mklauza_customproducturls_general_pattern_inherit').change();
    });
    
</script>



